import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable, "dark")}
      style={{ colorScheme: "dark" }}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b bg-background mb-4 md:mb-8">
          <div className="container mx-auto flex h-14 max-w-screen-2xl items-center justify-center px-4 md:px-8">
            <div className="flex items-center space-x-2">
              <span className="font-bold text-2xl tracking-tight">
                tomatoM4to Trading
              </span>
            </div>
          </div>
        </header>

        <main className="flex-1 flex flex-col">
          {children}
        </main>

        <footer className="border-t py-6 md:py-0">
          <div className="container mx-auto flex flex-col items-center justify-between gap-4 md:h-16 md:flex-row px-4 md:px-8">
            <p className="text-sm text-muted-foreground text-center md:text-left">
              &copy; {new Date().getFullYear()} tomatoM4to Trading.
            </p>
            <div className="flex items-center gap-4 text-sm text-muted-foreground">
              <a href="https://github.com/tomatoM4to" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors font-medium">
                @tomatoM4to
              </a>
              <span className="text-muted-foreground/50">|</span>
              <a href="https://github.com/tomatoM4to/Trading" target="_blank" rel="noopener noreferrer" className="hover:text-primary transition-colors font-medium">
                Trading Repository
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
